#!/bin/bash
#
# Usage: ./run 
# Compiles and runs the project. 

set -e

mkdir -p bin/data 
mkdir -p bin/lib 
scalac -d bin -classpath lib/commons-cli-1.2.jar src/main/scala/*
cp lib/* bin/lib 
cp data/* bin/data

cd bin
scala -classpath lib/commons-cli-1.2.jar:. Comp

